### ISSUE TITLE
node2nix is preferring http over https?

### ISSUE THREAD

**Issue by colemickens** [svanderburg/node2nix#114]
I'm not sure if the Issue title is accurate, but I'm not sure of a better summary.

When I tried to add a new node package to nixpkgs, it seems to have changed some of the dependency urls from `https` to `http`. Is this is a bug in `node2nix` ?

https://github.com/NixOS/nixpkgs/pull/48030

**Comment by svanderburg** [comment]
What kind of dependency is changed? Is it a dependency that refers to a package in the NPM registry, a Git repo specifier, or a raw HTTP URL?

I think the default registry URL setting is an HTTP URL in the code. Maybe I should change this to HTTPS.

**Comment by svanderburg** [comment]
I just did some investigation, and indeed: sometimes HTTPS URLs get updated to HTTP, which is really weird. Initially, I thought this was caused by the fact that the default registryURL setting in `node2nix` refers to `http://registry.npmjs.org`. Changing this to an HTTPS URL did not fix anything -- once in a while the generated Nix expressions still contains an HTTP URL.

I added some debug statements and it appears that the NPM registry itself is the culprit. The resulting config object sometimes seems to return an HTTP URL, e.g.:

```json
{"name":"finalhandler","description":"Node.js final http responder","version":"1.1.1","author":{"name":"Douglas Christopher Wilson","email":"doug@somethingdoug.com"},"license":"MIT","repository":{"type":"git","url":"git+https://github.com/pillarjs/finalhandler.git"},"dependencies":{"debug":"2.6.9","encodeurl":"~1.0.2","escape-html":"~1.0.3","on-finished":"~2.3.0","parseurl":"~1.3.2","statuses":"~1.4.0","unpipe":"~1.0.0"},"devDependencies":{"eslint":"4.18.1","eslint-config-standard":"11.0.0","eslint-plugin-import":"2.9.0","eslint-plugin-markdown":"1.0.0-beta.6","eslint-plugin-node":"6.0.1","eslint-plugin-promise":"3.6.0","eslint-plugin-standard":"3.0.1","istanbul":"0.4.5","mocha":"2.5.3","readable-stream":"2.3.4","safe-buffer":"5.1.1","supertest":"1.1.0"},"files":["LICENSE","HISTORY.md","index.js"],"engines":{"node":">= 0.8"},"scripts":{"lint":"eslint --plugin markdown --ext js,md .","test":"mocha --reporter spec --bail --check-leaks test/","test-ci":"istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --reporter spec --check-leaks test/","test-cov":"istanbul cover node_modules/mocha/bin/_mocha -- --reporter dot --check-leaks test/"},"gitHead":"024f493418f62a59592a98f07b23b265092c1006","bugs":{"url":"https://github.com/pillarjs/finalhandler/issues"},"homepage":"https://github.com/pillarjs/finalhandler#readme","_id":"finalhandler@1.1.1","_npmVersion":"5.6.0","_nodeVersion":"6.13.0","_npmUser":{"name":"dougwilson","email":"doug@somethingdoug.com"},"dist":{"integrity":"sha512-Y1GUDo39ez4aHAw7MysnUD5JzYX+WaIj8I57kO3aEPT1fFRL4sr7mjei97FgnwhAyyzRYmQZaTHb2+9uZ1dPtg==","shasum":"eebf4ed840079c83f4249038c9d703008301b105","tarball":"http://registry.npmjs.org/finalhandler/-/finalhandler-1.1.1.tgz","fileCount":5,"unpackedSize":16905},"maintainers":[{"name":"dougwilson","email":"doug@somethingdoug.com"}],"directories":{},"_npmOperationalInternal":{"host":"s3://npm-registry-packages","tmp":"tmp/finalhandler_1.1.1_1520357803698_0.8904166922156158"},"_hasShrinkwrap":false}
```

The code fragment above shows what the NPM registry returns in these cases: an HTTP URL to the package. `node2nix` simply uses that values that the NPM registry provides.

I think is probably an issue which the NPM registry maintainers need to know. Perhaps we should report this to them.

**Comment by colemickens** [comment]
https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285

**Comment by svanderburg** [comment]
It does not use `npm` in the derivation but it does use one of its APIs to fetch the metadata from the NPM registry, namely: `npm-registry-client`

The API call that returns the metadata sometimes contains an HTTP URL. Upgrading `npm-registry-client` to the latest version does not seem to help.

Yes, I can replace http:// with https:// if nothing else is possible, but better would be that the NPM registry maintainers fix this. By inspecting the content of the NPM community page, I think this is much more difficult for them than expected.

**Comment by svanderburg** [comment]
I think this problem is solved -- not that I have changed anything in the code, but it seems that the NPM registry maintainers have eliminated all http:// URLs. I just checked the latest generated `node-packages-v10.nix` and none of the packages or dependencies that originate from the NPM registry have http:// URLs -- they are all https:// now.
