### ISSUE TITLE
how to override src

### ISSUE THREAD

**Issue by srghma** [svanderburg/node2nix#143]
From https://github.com/justinwoo/easy-purescript-nix/pull/50

using command to generate files

```
src_dir=$(nix-build --quiet $script_dir/src.nix)

mkdir -p $script_dir/generated

node2nix \
  --input $src_dir/package.json \
  --lock $src_dir/package-lock.json \
  --nodejs-10 \
  --output $script_dir/generated/node2nix-node-modules.nix \
  --composition $script_dir/generated/node2nix-default.nix \
  --node-env $script_dir/generated/node2nix-node-env.nix
```

the `src` argument in file `node2nix-node-modules.nix` is relative

```
  args = {
    name = "pscid";
    packageName = "pscid";
    version = "2.6.0";
    src = ../../../../../../nix/store/hrvwwkjp9zgmicwxl25xkm8myvlzwzpf-source;
    dependencies = [
```

________________

the 

```
package.overrideAttrs (oldAttrs: rec {
  inherit src bowerComponents;

  buildInputs = oldAttrs.buildInputs ++ [ purs ];

  fixupPhase = ''
    cp --reflink=auto --no-preserve=mode -R $bowerComponents/bower_components .

    npm run build
  '';
})
```

doesnt help, because src is passed to `composePackage` function earlier

_________

Probable fixes:
- expose `args` and `sources` from `node2nix-node-env.nix`
- provide overriding mechanism that allows to override arguments to `buildNodePackage` function (probably function `package.passthrough.overrideNodePackage`

**Comment by svanderburg** [comment]
I'm still trying to make myself familiar with your use case, so that I can decide what a good strategy/change would be.

One question: is the relative `src` path the main reason why you want to do an override?

**Comment by srghma** [comment]
`is the relative src path the main reason why you want to do an override` yes, exactly, 

it generates `src = ../../../nix/store/asdfasdf`, this path is working only on my computer, but doesnt work on travis machine, I want to override the src

**Comment by svanderburg** [comment]
I'm a bit puzzled by the deployment process you're trying to implement. So it appears there is some Nix expression producing an NPM package with a `package.json` and `package-lock.json` file?

Where is the variable $script_dir referring to? Is this a Nix-based project that is stored somewhere? I can't find anything in the issue or in the `easy-purescript-nix` repository that has a `src.nix` file.

From the generated package, `node2nix` is used to generate Nix expressions but puts them in a different location?

This is a use case that I have not really used myself before in node2nix. My original use case for node2nix is to basically just use it as a replace for 'npm install' on project level. It expects that the Nix expressions and input JSON configurations live somewhere close together.

I'm trying to figure out what exactly is desired to package and what kind of operations we need to execute. Maybe there is an easier way to accomplish the same thing.

**Comment by svanderburg** [comment]
Ah I see. The changes are in your fork of that repository. So it seems `src.nix` is used to fetch the repository from github. Then the script uses that checkout to generate Nix expressions from.

**Comment by srghma** [comment]
@svanderburg, yes, and the `$script_dir` is the directory where the `update.sh` script is located. Allows to write files by absolute path.

**Comment by svanderburg** [comment]
Hmm, if I study your fork, then what you probably want is Nix to obtain a repository from GitHub, then use node2nix to generate expressions from it, and then again: deploy the project with Nix?

What you can also do is instead of using the `package.json` file from a development project (that you have to obtain by some external means first somehow), use the JSON specification to deploy packages. You can also write a JSON configuration like this:

```nix
[
  { "pscid": "kRITZCREEK/pscid#6bf65c5368fd997d980b7528f6fe39bd92fcc07a" }
]
```

and use node2nix to generate Nix expressions from that JSON configuration file:

```bash
$ node2nix -i pscid.json
```

Then the generated expression will download the repository with Nix (by using `fetchgit`) and uses Nix to deploy it.

Basically, package JSON specifications work with any NPM dependency specifier -- packages from the NPM registry, local directories, and Git repositories.

There is only one minor caveat in using this approach: `node2nix` deploys all packages in this JSON specification as NPM dependencies. `package-lock.json` files for such repositories are ignored, because that's also what NPM does -- NPM will only use lock files when deploying a project, not when you install dependencies. I think in almost all cases, this will still result in a working deployment, but the actual versions of the dependencies may slightly differ.

Maybe in a future version I should also make a new option allowing users to deploy remote development projects. The reason that this function does not exist yet, is because the "vanilla" NPM, does not have such a feature. In many Nix deployment workflows, however, we download development projects from remote git repos all the time.

**Comment by srghma** [comment]
@svanderburg tnx for your time on this issue

This approach:
1) yes, it ignores `package-lock.json`
2) this doesnt generate bower packages https://github.com/srghma/easy-purescript-nix/blob/656a9a48f5a592dc2a783eadab4e7a2476821326/pscid/update.sh#L22

**Comment by roberth** [comment]
I've done a little proof of concept that "fixes" this with `sed` among other things.

https://github.com/hercules-ci/ghcide-nix/pull/8/files#diff-c0d49b126ab5b388f95929f64fdefdeeR44-R53
