### ISSUE TITLE
ENOENT when using lock file

### ISSUE THREAD

**Issue by tyrion** [svanderburg/node2nix#154]
I was trying out `node2nix` with this [package-lock.json](https://github.com/Foundry376/Mailspring/blob/1.6.3/app/package-lock.json) but I get this error:

```bash
$ node2nix -v
node2nix 1.7.0
$ node2nix -l package-lock.json
fetching local directory: ./. from .
Error: ENOENT: no such file or directory, mkdir '/tmp/node2nix-git-checkout-@bengotow/slate-edit-list2019817-12083-ilnks8.bcgo9'
```

**Comment by svanderburg** [comment]
Do you also have an ordinary `package.json` in the same folder? You actually need both in order for a deployment to work.

**Comment by svanderburg** [comment]
I just checked. It's indeed a bug. For some weird reason the temp directory is not created.

**Comment by svanderburg** [comment]
Hmm it was a really strange error, but it seems that it is also possible to have scoped packages that are downloaded from Git repositories, causing the directory creation to fail because of the slash in the name.

Revision: af3d8f79cc98c803f53c517a0a976c4338359ec1 should have this fixed.

Can you try installing the latest development version of node2nix and check if it works for you? The instructions how to do this are in the README.md file.

**Comment by svanderburg** [comment]
I believe this is fixed. Version 1.8.0 was release very recently that includes the fix I'm referring to in the previous message.
