### ISSUE TITLE
attribute 'nodejs-6_x' missing

### ISSUE THREAD

**Issue by 11111000000** [svanderburg/node2nix#164]
```
installing 'node-parcel-1.12.4'
error: attribute 'nodejs-6_x' missing, at /tmp/nix-npm-
install/parcel/default.nix:5:48                       
(use '--show-trace' to show detailed location informati
on)                                                   
~/Work
```

with that script in .config/nixpkgs/config.nix:
```
{ pkgs, ... }:


{  
  packageOverrides = super: {
    
    nix-npm-install = pkgs.writeScriptBin "nix-npm-install" ''
      #!/usr/bin/env bash
      tempdir="/tmp/nix-npm-install/$1"
      mkdir -p $tempdir
      pushd $tempdir
      # note the differences here:
      ${super.nodePackages.node2nix}/bin/node2nix --input <( echo "[\"$1\"]")
      nix-env --install --file .
      popd
    ''; 
  };
}

```

**Comment by svanderburg** [comment]
Hi, which version of node2nix are you using? Recent versions have switched to newer versions by default. 

Newer versions of Nixpkgs no longer have Node.js 6.x, because it has reached end-of-life.

However, the generator still allows you to generate expressions for older versions if that is desired. If you want to deploy a Node.js 6.x package you should downgrade your Nixpkgs installation to version 19.03 or lower.

Alternatively, try upgrading node2nix to the latest version and use a parameter to target a new version, e.g. `--nodejs-12`.

**Comment by svanderburg** [comment]
Closing this. Assuming that this explanation suffices. If not, please reopen.
