### ISSUE TITLE
webpack and paths resolution

### ISSUE THREAD

**Issue by paluh** [svanderburg/node2nix#167]
Hi,

I'm trying to use `node2nix` + `pkgs.nodePackages` as the only way to install my project dependencies. It works great so far. Thanks for building this incredible tool! 

The problem started when I tried to introduce webpack into my build chain. Without any additional `resolve` configuration it complains about missing modules  `Module not found: Error: Can't resolve ...`.
It turned out that [weback doesn't want to take `NODE_PATH`](https://github.com/webpack/webpack/issues/4479) into account during its module resolution process. Additionally when its configuration contains only absolute paths it doesn't search for dependencies in `node_modules` package subdirectories so I was forced to add `"node_modules"` to its config (even though I don't have local node_modules dir in my project). Finally I was able to provide working webpack config which works for me by using something like:

```javascript
  resolve: {                                                                                                                                                                               
   modules: ['node_modules', ...process.env.NODE_PATH.split(':')]                                                                                                                         
  },
```

in my webpack configuration.  

I just want to ask if this seems to you as a preferred way to work with webpack + node2nix or if I missed something obvious here.

**Comment by bbigras** [comment]
I think I have the same problem trying to build a webapp created with `create-next-app`.

**Comment by svanderburg** [comment]
I assume that you are using a nix-shell session using the `shell` attribute generated with node2nix, e.g. `nix-build -A shell` ?

The problem is that an "ordinary" NPM workflow in some conditions is difficult to simulate "the Nix way". All dependencies are obtained by Nix and stored in isolation in the Nix store.

Nix, by design, can only put stuff in the Nix store and not in any other locations of the filesystem!

In many development projects (that are managed by build tools, such as grunt, gulp, eslint or webpack) the common practice to have a writable `node_modules/` sub folder in the project.

Tools, such as grunt, typically use this sub folder to look for plugins. 

The only "workaround" I see is to just make a symlink in your project to the corresponding Nix store path that contains the node_modules. You can easily do that by running:

```bash
ln -s $NODE_PATH node_modules
```

and then it should work.

Of course, you should remove this symlink again if you intend to use `nix-build` or `nix-env` to deploy your package, otherwise it screws up the deployment.

**Comment by svanderburg** [comment]
@paluh @bbigras 
I'm not sure if this answers your questions, but since this is a question I have received more often, I should probably add a section about it to the README.md file.

**Comment by svanderburg** [comment]
I have added an extra note to the troubleshooting section: 68d0a00

**Comment by svanderburg** [comment]
Assuming that the extra clarification in the `README.md` suffices. If not, please reopen.
