### ISSUE TITLE
chmod: missing operand after 'u+w'

### ISSUE THREAD

**Issue by dckc** [svanderburg/node2nix#21]
If I invoke `node2nix` and then `nix-build` in a newly created directory (`/tmp/x`) containing this `package.json` file:

``` json
{
    "name": "hiho",
    "version": "0.1.0",
    "dependencies": {
        "Capper": "dckc/Capper#package"
    }
}
```

I get:

```
connolly@pav:/tmp/x$ nix-build
these derivations will be built:
  /nix/store/2plbgsqxq4wyydvb6f6hq4zr80g2rm7c-node-hiho-0.1.0.drv
  /nix/store/cd6jxmansn4rbz6mbgjsd3whzlkhrran-node-tarball-hiho-0.1.0.drv
  /nix/store/gfvx0m0b8cbhn89y09x1h9fr1alnhgla-node-dependencies-hiho-0.1.0.drv
  /nix/store/lwflcg7rvbs448fg1bjqf6y0jarxr4yk-node-shell-hiho-0.1.0.drv
building path(s) ‘/nix/store/wry2nkn67lxavy9jcvxqycllxcg187vd-node-hiho-0.1.0’
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
installing
unpacking source archive /nix/store/hnmqxhgsywj2dk5gwyc42j0if6sa0abn-x
chmod: missing operand after 'u+w'
Try 'chmod --help' for more information.
builder for ‘/nix/store/2plbgsqxq4wyydvb6f6hq4zr80g2rm7c-node-hiho-0.1.0.drv’ failed with exit code 1
error: build of ‘/nix/store/2plbgsqxq4wyydvb6f6hq4zr80g2rm7c-node-hiho-0.1.0.drv’ failed
```

**Comment by svanderburg** [comment]
I think this problem is caused by running the latest released version in conjunction with the latest (unstable) Nixpkgs master version. The function in the generic builder that computes the stripped name of a Nix store path has changed.

Can you try installing the latest development version, e.g. by checking out this repository and running:

    $ nix-env -f release.nix -iA package.x86_64-linux

We have recently applied a fix for that, but it isn't part of any release yet.

**Comment by dckc** [comment]
Thanks for the suggestion, but now I get `npm ERR! code ENOGIT`.

I have git installed both via an Ubuntu package and in my nix environment.

```
connolly@pav:/tmp/x$ type git
git is hashed (/home/connolly/.nix-profile/bin/git)
connolly@pav:/tmp/x$ ls -l /home/connolly/.nix-profile/bin/git
lrwxrwxrwx 1 connolly connolly 62 Dec 31  1969 /home/connolly/.nix-profile/bin/git -> /nix/store/ns165xwkzlq13zqf43hl81n8k4j78vdy-git-2.10.1/bin/git
```

More details are in [npm-debug.log](https://github.com/svanderburg/node2nix/files/560102/npm-debug.log.txt)

**Comment by dckc** [comment]
I get the same symptoms inside a fresh `docker run --rm -ti nixos/nix bash` container.

**Comment by dckc** [comment]
I added git to `buildInputs` (IOU diff) but now I get:

```
npm ERR! argv "/nix/store/qws0npzb3rzxqa7adz5zikay7i4f4p78-nodejs-4.6.0/bin/node" "/nix/store/qws0npzb3rzxqa7adz5zikay7i4f4p78-nodejs-4.6.0/bin/npm" "--registry" "http://www.example.com" "--nodedir=/nix/store/zk52c4zyivnnifgpxnprjjnziq0g5nji-node-sources" "--production" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9

npm ERR! Unexpected token <
npm ERR! <!doctype html>
...
```

[npm-debug.log](https://github.com/svanderburg/node2nix/files/560153/npm-debug.log.txt)

**Comment by svanderburg** [comment]
It seems that NPM is trying to invoke git to figure out to which revision the '#package' tag resolves to.

To circumvent NPM from invoking git, I use to substitute such version identifiers by wildcards '*' (the node-env.nix file has some functionality for doing this), but apparently for GitHub URLs this functionality is missing. It does work for "ordinary" Git URLs though.

I have been thinking for a while to implement a completely different approach -- instead of substituting these version identifiers (which sometimes confuses NPM), I create a fake 'git' command that "fools" npm. Then I don't need to change a package.json configuration file at all, still making npm believe that it using the right versions.

I think until this new hack is completed, you should either substitute this github url by a real git+https:// url, or override the expression to not run 'npm install' (see README.md for more information).

**Comment by dckc** [comment]
yay! Using `git+https://github.com/dckc/Capper.git` works great.
