### ISSUE TITLE
i wanna install [ "ink" ] 

### ISSUE THREAD

**Issue by PlumpMath** [svanderburg/node2nix#294]
[ "react" ] works fine.
I haven't tested the rest, but I'm worried that there are many things that won't work.

``
error: builder for '/nix/store/alrsqfp0cqhf5im0j1h22q5gx9ll8jwq-ink-3.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > npm WARN old lockfile     at async fetch (/nix/store/gx91ndd69gm0q0rlcs2lm48kjfr91v7m-nodejs-16.14.2/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
       > npm WARN old lockfile     at async Array.<anonymous> (/nix/store/gx91ndd69gm0q0rlcs2lm48kjfr91v7m-nodejs-16.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:759:9) {
       > npm WARN old lockfile   code: 'ENOTCACHED'
       > npm WARN old lockfile }
       > npm ERR! code ENOTCACHEDsill idealTree buildDeps
       > npm ERR! request to https://registry.npmjs.org/@sindresorhus%2ftsconfig failed: cache mode is 'only-if-cached' but no cached response is available.
       >
       > npm ERR! A complete log of this run can be found in:
       > npm ERR!     /private/tmp/nix-build-ink-3.2.0.drv-0/.npm/_logs/2022-04-26T22_12_10_054Z-debug-0.log
       >
       For full logs, run 'nix log /nix/store/alrsqfp0cqhf5im0j1h22q5gx9ll8jwq-ink-3.2.0.drv'.

**Comment by svanderburg** [comment]
I'm currently investigating the situation. What I already know is that for newer NPM versions (that work with lockfile version 2), sometimes information is missing, and as a result, NPM tries to fetch that missing information from the NPM registry. Since network access is restricted in regular Nix derivations, this will fail.

The v2 lockfile format is an hybrid between the v1 and v3 formats, because the latter is not backwards compatible.

The proper solution would be to also support v3 lock files, but providing this will not be an easy change.

It should still be possible to get a successful installation to bypass the NPM install step (see README.md for more information on how to do this).

**Comment by PlumpMath** [comment]
I don't know what to do.
Could you please leave an example of installing the ink package by way of like your blog?
Even after reading the readme file, I didn't know where to start. y.g Thanks.

**Comment by PlumpMath** [comment]
https://discourse.nixos.org/t/nodejs-application-in-nix/16196/2

https://github.com/svanderburg/node2nix/issues/275#issuecomment-994007054

I hope this solves it.

**Comment by PlumpMath** [comment]
The packages are now installed.  However, it is not imported from node.  I think I've been obsessed with something for the past few months. I need to know exactly where the problem was...  As you said, did you downgrade the version again from the nodejs side?  However, the current problem that is not called in repl seems to be a problem on the nix side.  I returned to flake in the old legacy way, but I'll have to check where the node_modules folder is in flake.
