### ISSUE TITLE
Support NodeJS 8

### ISSUE THREAD

**Issue by copumpkin** [svanderburg/node2nix#55]
It isn't currently supported and it would be nice if it were

**Comment by copumpkin** [comment]
@joepie91 points out that this is more about supporting a different NPM version than supporting a new node version

**Comment by svanderburg** [comment]
Yes, I'm already working on it, but this will take time.

From all my investigations so far, it seems we need yet another radically different approach. :(

The biggest challenge is that NPM 5.x will always consult the (brand-new content-addressable) cache whenever it encounters a dependency -- in a Nix builder environment the cache is (obviously) always empty. This means NPM will always attempt to download packages, which is not desirable, since in pure environments network access is restricted.

Contrary to NPM 4.x and older, it does not seem to ignore dependencies when they have been provided by other means. So this means I cannot use anything from the build function that has been developed for the older NPM releases.

The only solution I see so far is that we populate the cache ourselves by some other means, and then we run NPM in offline mode, but this new approach requires a new generator, new builder function and new generator.

I already have a very minimalistic proof-of-concept implementation (not pushed online yet), that seems to be promising. In this experiment, I'm using NPM's newer APIs (e.g. pacote, cacache) and I'm able to populate the cache with tarballs from the registry. I can run NPM in offline mode and it seems to work just fine.

However, the proof-of-concept tool is not at all usable at the moment and mostly just a collection of trials + hacks.

**Comment by wmertens** [comment]
Just providing moral support here :) Using NPM's own APIs seems like a winning idea.

I wonder, can't we patch NPM to fix undesirable build-time behavior with a flag? Maybe they'd accept such a patch upstream.

**Comment by proger** [comment]
In the meantime i've come up with this super-weird dance :) https://gist.github.com/proger/40e12a0f7ac7bd2d261b98b69cd99327

**Comment by wmertens** [comment]
@proger, won't that keep your service down until the build succeeds?

**Comment by proger** [comment]
Yeah, it's as runtime as it gets, but that's what I've ended up doing for more kinds of stuff that needs extensive packaging work and the value from having this software deployed is yet unclear :)

**Comment by svanderburg** [comment]
For the impatient, I have created a `npm5` branch that contains some very experimental/basic support: https://github.com/svanderburg/node2nix/tree/npm5

What is currently supported:
* Deployment of development projects that include a `package-lock.json` file
* Generating Nix expressions from a `package-lock.json` file (including git hash computations)
* Hacky stuff that seems to bypass the NPM cache in most scenarios
* nix-shell support

Unsupported:
Many things, most notably:
* Deployment of development projects without a `package-lock.json` file.
* Some git dependencies still cause deployment failures
* Deployment of third party packages

How to use:
Install the project with:

```bash
nix-env -f default.nix -iA package
```

Run the following command to generate Nix expressions:

```bash
node2nix -8 -l package-lock.json
```

**Comment by svanderburg** [comment]
Everything is now feature complete. As a result, I merged the `npm5` into `master`.

It still requires a bit of testing and could use some usability improvements. Most importantly, deploying from `package-lock.json` files could be tested a bit more.

**Comment by lukeadams** [comment]
semi-related: seems like nodejs-7_x was removed in nixpkgs-unstable as per https://github.com/NixOS/nixpkgs/pull/27955 , breaking the -7 flag

**Comment by alexfmpe** [comment]
Trying to apply node2nix to some stuff that requires node 8.
Is there a planned date to add 1.5.0 to nixpkgs?
At the moment I'm using `default.nix` from this repo.

**Comment by svanderburg** [comment]
@alexfmpe 
Yes it will be updated very soon, probably within next the coming days.

The only thing I need to do is wrapping some small things up and finishing the blog post.

If you to help test it as much as you can with Node.js 8/NPM 5 specific scenarios, such as deploying from lock files.

**Comment by svanderburg** [comment]
Closing this, since it is now supported.

**Comment by copumpkin** [comment]
Thanks!! Very excited to try it 😄
