### ISSUE TITLE
Document status

### ISSUE THREAD

**Issue by williammpratt** [svanderburg/node2nix#61]
Since some issues are almost a year open and the scope of this project seems limited, it appears rather unmaintained. Does this have any production users or is this just a hobby project?

Ironically, no version of nixpkgs is mentioned that should work. The nixpkgs master branch doesn't work with node2nix. 

Any non-trivial project will also have references to private git repositories. You don't even discuss a recommended setup. How exactly do you expect people to use this and on which platforms, if at all?

**Comment by svanderburg** [comment]
Yes this project has plenty of users -- its primary purpose is to support my own projects and those of my employer.

However, as with many free/open-source projects (including many Nix-related sub projects), this tool is mostly an voluntary effort -- there is no company backing its development, I have a full time job next to my Nix-related work and much of its development is done in my spare time.

As a result, it is impossible to always give hard commitments to all issues. For some periods of time, I can solve many of them, for others I there is not much I can do. Furthermore, not all issues are very urgent.

From your description, I noticed that you have two kinds of issues: you seem to be having problems using node2nix with the latest master revision of Nixpkgs. I just checked and my use cases work fine. Can you elaborate a bit more about a specific scenario that does not work for you and create a separate issue for that? Then I may be able to solve that problem for you.

Private Git repositories are currently unsupported, simply because of the reason that I have never used them so far. Furthermore, dealing with private git checkouts in Nixpkgs is also a bit of a challenge.  Can you create an issue for this specifically? Private Git repo support is something that is worth adding.
