### ISSUE TITLE
Overriding package dependencies - are docs up to date?

### ISSUE THREAD

**Issue by paluh** [svanderburg/node2nix#62]
I can probably be wrong as I'm NixOs newbie, but in `README` there is a section "Adding unspecified dependencies" and in following snippet there is:
   ```nix
     nodePackages = import ./default.nix
     ...
     nodePackages // {
             floomatic = nodePackages.floomatic.override ...
   ```
I'm trying to follow this scenario, but I'm not able to override any package... I'm not sure if I'm reading code correctly but `default.nix` is an expression which evaluates to ` import ./node-packages.nix {   ... }` and `node-packages.nix` evaluates to 

   ```nix
    {
      tarball = nodeEnv.buildNodeSourceDist args;
      package = nodeEnv.buildNodePackage args;
      shell = nodeEnv.buildNodeShell args;
    }
   ```
So it seems that `nodePackages` is just set with `package`, `shell` and `tarball` attributes and there is no `floomatic` (or any other package to override) there. Am I right?

**Comment by svanderburg** [comment]
The reason why it does not work is because the expressions that you have generated are derived from a `package.json` file of a development project (producing the corresponding development Nix expressions for it), while the override expression overrides a package for a collection expression (an array of packages).

If you want to make to override work, you should either:

* Define a collection expression that includes the package and override that with the convention that you are currently using
* Change the override in such a way that it overrides the `package` derivation:

```nix
nodePackages.package.override { ... }
```

**Comment by svanderburg** [comment]
Closing, since I believe this answer clarifies the problem.
