### ISSUE TITLE
Private git support

### ISSUE THREAD

**Issue by williammpratt** [svanderburg/node2nix#66]
I would like to see private git support where all the fetching is done with minimal and easy to setup credentials. Additionally, there should be network caching and it should be efficient. 

Making a small change in one of the files should not result in huge rebuild times.

**Comment by svanderburg** [comment]
I just added initial support for private git repositories in revision https://github.com/svanderburg/node2nix/commit/0ca808cbbb9c073c525d298c97a06edc4a8e1ff5 since I also have a use case for it.

It builds on top of the `fetchgitPrivate` function in Nixpkgs, but does not try to improve it, hence it suffers from the same limitations.

Discussion about the fetchgitPrivate function should be done here: https://github.com/NixOS/nixpkgs/issues/32732
