### ISSUE TITLE
node2nix failing to select dependency when it did previously

### ISSUE THREAD

**Issue by eqyiel** [svanderburg/node2nix#67]
I have an issue with `node2nix` selecting the wrong version of `loader-utils` in a package I'm working on:

https://github.com/vector-im/riot-web/issues/5749

There are two versions of that package that end up in `node-packages.nix`: 

https://github.com/eqyiel/riot-electron-nix/blob/node2nix-hoisting-bug/node/node-packages.nix#L2260-L2268
https://github.com/eqyiel/riot-electron-nix/blob/node2nix-hoisting-bug/node/node-packages.nix#L8065-L8073

But webpack doesn't receive the correct version: https://github.com/eqyiel/riot-electron-nix/blob/node2nix-hoisting-bug/node/node-packages.nix#L9299-L9303

Note that it _did_ receive the correct version at one point: https://github.com/Ralith/riot-electron-nix/blob/master/node/node-packages.nix#L9217

I'm a bit stumped about how to debug this further, any suggestions would be greatly appreciated.

**Comment by svanderburg** [comment]
Maybe it could have been caused by a refactoring bug that I recently discovered. The procedure that tries to "lift" packages in the `node_modules/` dependency tree seems to incorrectly replace dependencies in some scenarios. It is actually quite hard to discover and reproduce, as it only happens in very rare cases.

Anyway, it has been fixed in revision acc5a50c2e9a838b1ae9e7dcbf53898b4e4ea9c5

Can you try the development version and see if it works for you? It can be installed as follows:

```bash
nix-env -f default.nix -iA package
```

**Comment by eqyiel** [comment]
@svanderburg that does indeed fix the problem, thanks for checking it out!
