### ISSUE TITLE
How to include package in my derivation Properly?

### ISSUE THREAD

**Issue by Rizary** [svanderburg/node2nix#80]
I have default.nix like the following

```
{ nixpkgs ? import <nixpkgs> {}
}:

let
  inherit (nixpkgs) pkgs;
  frontend = import ./frontend {};
  backend = import ./backend {};

in
  pkgs.stdenv.mkDerivation {
    name = "app";
    src = ./.;
    unpackPhase = ''
      cp -r $src/static/* .

    '';

    installPhase = ''
      mkdir -p $out/prod/static
      cp -rf ${frontend}/ghcjs/frontend/bin/frontend-exe.jsexe/* $out/prod/static/
      cp -rf ${backend.package}/lib/node_modules/backend/result/lib/node_modules/backend/* $out/prod/
    '';

    phases = ["unpackPhase" "installPhase"];
      
  }`
```
notice that in my `$out` file, i got 2 result.. so i use the ` cp -rf ${backend.package}/lib/node_modules/backend/result/lib/node_modules/backend/*` and it feels not right to me. It should just `${backend.package}/lib/node_modules/backend/`. If i put only that, i got 1 folder result.

How can I use my backend and put it in my installPhase?

**Comment by svanderburg** [comment]
If I understand your question correctly, then you don't seem to be having problems including your package, but you don't know how to do it properly?

From the information that you haven given me, it is hard to judge. Anyway, from what I have seen so far, I would recommend you to the following things:

* For importing the packages (`frontend` and `backend`), also propagate the `pkgs` and `system` parameters. This is to be sure that the package set configuration matches the one you have imported earlier.

I would do something like this:

```nix
let
  system = builtins.currentSystem;
  pkgs = import <nixpkgs> { inherit system; };
  frontend = import ./frontend { inherit pkgs system; };
  backend = import ./frontend { inherit pkgs system; };
in
...
```

* I would also try to symlink the `node_modules` as opposed to copying them with `cp -rf`, but that may not always work, depending on your use case. I know, for example, that if certain modules have shared dependencies then they cannot be found because the CommonJS module system internally dereferences symlinks first and looks relative from there. I would try the symlink approach first and if that does not work, copying recursively.
* I assume that `backend` and `frontend` are generated Nix expression sets. You can also shared the corresponding `node-env.nix` expression by using the `-e` and `--no-copy-node-env` parameter. This is, for example, something the bootstrap script does: https://github.com/svanderburg/node2nix/blob/master/bootstrap.sh

**Comment by Rizary** [comment]
Hi,

Thank you very much. It seems that I didn't do it properly. Thanks for your input also.
