### ISSUE TITLE
Package builds fail if node_modules directory is populated in src

### ISSUE THREAD

**Issue by nicknovitski** [svanderburg/node2nix#88]
For example, in this repository: 
```
$ cd tests/lockfile
$ npm install
# ...
$ nix build -f . package
builder for '/nix/store/3h7vx80crfq2i62bp2dacc6y15waiwk3-node-lockfile-0.0.1.drv' failed with exit code 1; last 9 log lines:
  unpacking sources
  patching sources
  configuring
  no configure script, doing nothing
  building
  installing
  unpacking source archive /nix/store/4qvd9mhzc59y84fsif5sxy54aljyknvk-lockfile
  unpacking source archive /nix/store/06r85md5svxxcqj50667i9lf5n83nnpf-testa
  mv: cannot overwrite non-directory '/nix/store/si8xsvgvkvnilbgfc2fb42rnzljhcl06-node-lockfile-0.0.1/lib/node_modules/lockfile/node_modules/testa' with directory 'testa'
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/3h7vx80crfq2i62bp2dacc6y15waiwk3-node-lockfile-0.0.1.drv' failed
```

Should there be a source filter?  Should the builder delete the node_modules folder if it already exists?

**Comment by svanderburg** [comment]
Yes and no.

You're mostly right -- in most cases, you indeed don't want a bundled `node_modules/` to end up in your Nix builder environment -- if you use NPM to install packages in your project directory and then use node2nix, the bundled dependencies are used instead of the dependencies deployed by the Nix package manager. This may lead to unexpected/unpredictable results.

On the other hand, there are also Node.js projects that may have bundled dependencies in the `node_modules/` folder that also have local modifications. In such cases, you actually do want to include these bundled packages in the builder environment.

Maybe displaying a warning to the user could be a good solution -- it still allows someone to use bundled dependencies in these exceptional cases and (hopefully) takes away the confusion that a user may face.

**Comment by nicknovitski** [comment]
That makes a lot of sense.  A warning could be nice, like the warning when a package-lock.json file is present but not used.

**Comment by svanderburg** [comment]
I added a warning feature in revision 3b24fb4903a872a5b19115d0e9ce27083bb12126 that reminds the user about the `node_modules/` folder in the project directory. I have also seen too many people running into this problem that typically goes unnoticed.
